export type CaseStudy = {
  slug: string;
  title: string;
  client: string;
  category: string;
  year: number;
  hero: string;
  gallery: string[];
  video?: string;
  brief: string;
  scope: string[];
  story: string;
  outcome: string;
  related: string[];
};

export const cases: CaseStudy[] = [
  {
    slug: "cio-association-corporate-performance",
    title: "CIO Association — Corporate Performance Night",
    client: "CIO Association",
    category: "Corporate Events",
    year: 2024,
    hero: "/portfolio/portfolio-14.jpg",
    gallery: ["/portfolio/portfolio-14.jpg", "/portfolio/portfolio-07.jpg", "/portfolio/portfolio-15.jpg", "/portfolio/portfolio-08.jpg"],
    video: "/media/portfolio-videos/cio-corporate.mp4",
    brief: "CIO Association approached us for their annual corporate performance night in Chennai — a mix of keynote, awards and a high-production evening entertainment show for 400+ CTO and CIO guests across Tamil Nadu's enterprise community.",
    scope: ["Stage design and setup", "Lighting and AV production", "Choreography and performance direction (via SATZ Dance Company)", "Guest flow and VIP handling", "Live photography and highlight reel", "Post-event recap video"],
    story: "The brief was to end the formal awards portion with an entertainment segment that would have senior enterprise leaders talking the next morning. We designed a stage with a wide LED backdrop, programmed sync-light sequences with the choreography, and produced a 12-minute performance arc that moved from classical opening to high-energy finale. The lighting rig was programmed to colour-match the brand's own purple-blue identity on screen so every photo looked on-brand.",
    outcome: "The reel from the night (embedded above) was reshared by CIO Association across their LinkedIn and WhatsApp communities within 48 hours. Three enterprise clients from the audience reached out for their own events in the following month.",
    related: ["accsys-5th-annual-fest", "octave-festival-north-east", "rotary-awards-thanksgiving"],
  },
  {
    slug: "octave-festival-north-east",
    title: "Octave 2023 — Festival of North East",
    client: "Ministry of Culture, Government of India",
    category: "Cultural & Government",
    year: 2023,
    hero: "/instagram-events/event-12.jpg",
    gallery: ["/instagram-events/event-12.jpg", "/instagram-events/event-11.jpg", "/instagram-events/event-19.jpg", "/portfolio/portfolio-04.jpg"],
    brief: "Produced the Chennai leg of Octave, Ministry of Culture's flagship festival showcasing the arts and crafts of India's North East. The brief covered a multi-day cultural showcase with performer hospitality, stage design and audience management across traditional and contemporary programming.",
    scope: ["Multi-day stage design and build", "Lighting and AV for cultural performances", "Hospitality for 150+ performers and delegates", "Audience management and guest flow", "Media and documentation coordination", "Government protocol liaison"],
    story: "Octave is where cultural accuracy meets production polish. We built the stage around traditional North Eastern architectural motifs — bamboo accents, warm uplighting, lantern-style installations — while running concert-grade sound and lighting underneath so classical and contemporary acts could switch without a technical hiccup. The group photo (shown above) was the closing-night family shot: performers from eight states and our Chennai team.",
    outcome: "The festival ran across its full programming schedule without a single technical disruption. Ministry of Culture retained Aerollerz for subsequent cultural programming in Chennai.",
    related: ["accsys-5th-annual-fest", "cio-association-corporate-performance", "rotary-awards-thanksgiving"],
  },
  {
    slug: "accsys-5th-annual-fest",
    title: "Accsys 5th Annual Fest — Team Celebration",
    client: "Accsys",
    category: "Corporate Events",
    year: 2023,
    hero: "/instagram-events/event-13.jpg",
    gallery: ["/instagram-events/event-13.jpg", "/instagram-events/event-15.jpg", "/portfolio/portfolio-14.jpg"],
    brief: "Produced the 5th Annual Fest for Accsys — a full-team celebration night ending with a sparkler-reveal grand finale designed to be the team's photo of the year.",
    scope: ["Theme and stage design", "Entertainment programming", "Lighting and sparkler-safe pyro design", "Catering coordination", "Team photo moment orchestration", "Live videography"],
    story: "Accsys wanted a night that didn't feel corporate — the kind of event where leadership and freshers end up on the same dance floor by 10pm. We built around that: lower stage, in-the-round seating, more lounge zones than head tables, and a grand finale sparkler reveal with every team member on stage. The photo (above) was the moment.",
    outcome: "Internal NPS for the event hit 92. Accsys retained us for subsequent annual events.",
    related: ["cio-association-corporate-performance", "octave-festival-north-east", "blm-housing-grand-birthday"],
  },
  {
    slug: "rotary-awards-thanksgiving",
    title: "Rotary — Awards & Thanksgiving Ceremony",
    client: "Rotary International",
    category: "Award Ceremonies",
    year: 2023,
    hero: "/instagram-events/event-10.jpg",
    gallery: ["/instagram-events/event-10.jpg", "/portfolio/portfolio-10.jpg", "/portfolio/portfolio-16.jpg"],
    brief: "Produced Rotary's annual Awards & Thanksgiving ceremony recognising community service across the Chennai district. The brief emphasised dignity, respect for honourees' stories, and crisp execution for a mixed-generation audience.",
    scope: ["Stage and award presentation design", "Backdrop and signage", "Lighting and sound", "Guest coordination and VIP seating", "Live photography and video documentation"],
    story: "A Rotary awards night isn't about theatrics — it's about honour. We designed the stage with a quiet dignity: cream and gold palette, dimmed house lights for each citation, a single spotlight on the recipient, and a soft brand presence that never competed with the honourees. Every citation ran within 90 seconds.",
    outcome: "Awards segment completed on time; multiple honourees quoted the staging in their acceptance notes.",
    related: ["cio-association-corporate-performance", "accsys-5th-annual-fest", "octave-festival-north-east"],
  },
  {
    slug: "blm-housing-grand-birthday",
    title: "BLM Housing Society — Founder's Grand Birthday",
    client: "BLM Housing Society",
    category: "Private Events",
    year: 2024,
    hero: "/portfolio/portfolio-11.jpg",
    gallery: ["/portfolio/portfolio-11.jpg", "/portfolio/portfolio-06.jpg", "/portfolio/portfolio-12.jpg"],
    video: "/media/portfolio-videos/blm-birthday.mp4",
    brief: "Grand birthday celebration for the founder of BLM Housing Society — a milestone function featuring an epic entry by SATZ Dance Company, tribute performances, and a gala format for 300 guests.",
    scope: ["Theme and stage design", "Entry choreography (via SATZ Dance Company)", "Lighting, pyro and sound", "Guest hospitality", "Tribute video production", "Live documentation"],
    story: "A founder's milestone birthday is partly a party, partly a legacy moment. We designed an entry sequence that moved from traditional welcome through a choreographed dance arc that referenced his career milestones. The grand finale had the whole family on stage with pyro columns and the audience on their feet.",
    outcome: "The entry sequence video went viral in the BLM community network within a week.",
    related: ["ocean-spray-resort-night", "accsys-5th-annual-fest", "cio-association-corporate-performance"],
  },
  {
    slug: "ocean-spray-resort-night",
    title: "Ocean Spray Resort — Private Celebration",
    client: "Private (confidential)",
    category: "Private Events",
    year: 2024,
    hero: "/portfolio/portfolio-06.jpg",
    gallery: ["/portfolio/portfolio-06.jpg", "/portfolio/portfolio-16.jpg", "/portfolio/portfolio-11.jpg"],
    video: "/media/portfolio-videos/ocean-spray.mp4",
    brief: "A high-end private evening at Ocean Spray Resort — a night where the resort was transformed into a celebration venue with full ambient lighting, floral treatment and curated entertainment for an intimate guest list.",
    scope: ["Resort-wide ambient lighting", "Floral and foliage styling throughout venue", "Entertainment programming", "Hospitality and guest flow", "Photo-worthy environmental styling"],
    story: "The brief was 'not a party — a statement.' We treated the entire resort as the venue, not just the main hall: pathway lighting, palm uplight, floral stations at every corner, a stage programmed to feel like extension of the resort architecture. By 9pm, guests had stopped looking at phones and started looking around.",
    outcome: "The host's one line to us at the end: 'This is the one people will remember.'",
    related: ["blm-housing-grand-birthday", "accsys-5th-annual-fest", "cio-association-corporate-performance"],
  },
  {
    slug: "puberty-function-traditional-decor",
    title: "Puberty Function — Traditional Décor",
    client: "Private (family)",
    category: "Cultural Decor",
    year: 2024,
    hero: "/portfolio/portfolio-03.jpg",
    gallery: ["/portfolio/portfolio-03.jpg", "/portfolio/portfolio-11.jpg", "/instagram-events/event-14.jpg"],
    video: "/media/portfolio-videos/tradition-decor.mp4",
    brief: "A manjal neerattu vizha (puberty function) celebration where the family wanted a traditional Tamil cultural setup — not the usual banquet-hall template.",
    scope: ["Traditional décor design (brass, marigold, mango leaves, kolam)", "Mandap and seating setup", "Floral styling", "Welcome and entry zone", "Photography coordination"],
    story: "Tradition meets elegance was the brief. We leaned into the cultural specifics — brass vessels, marigold strings, kolam entry, mango-leaf toran — but staged it with photographer-grade lighting so the family photos came out as portrait-ready, not harsh-flash flat.",
    outcome: "The family's photographer specifically noted the lighting setup as 'the easiest wedding-like event I've shot all year.'",
    related: ["blm-housing-grand-birthday", "accsys-5th-annual-fest", "ocean-spray-resort-night"],
  },
  {
    slug: "dance-floor-choreography",
    title: "The Dance Floor is Open — Live Entertainment",
    client: "Private",
    category: "Live Entertainment",
    year: 2024,
    hero: "/instagram-events/event-14.jpg",
    gallery: ["/instagram-events/event-14.jpg", "/instagram-events/event-16.jpg", "/instagram-events/event-17.jpg", "/instagram-events/event-18.jpg"],
    video: "/media/portfolio-videos/dance-floor.mp4",
    brief: "Live entertainment production for a private celebration — a full dance programme designed to open the evening with high energy and keep guests on the floor for the night.",
    scope: ["Choreography direction (via SATZ Dance Company)", "Stage and dance-floor design", "Lighting programming synced to music", "Entry MC and host coordination", "Music and sound engineering"],
    story: "The team wanted a programmed opening that transitioned organically into open-floor dancing. We built a 20-minute opener with the SATZ Dance Company team, with lighting cued to each phrase, that ended by inviting guests onto the floor. From that moment to midnight, the floor never cleared.",
    outcome: "Standard quote from the host afterwards: 'Nobody left until the end.'",
    related: ["blm-housing-grand-birthday", "cio-association-corporate-performance", "ocean-spray-resort-night"],
  },
  {
    slug: "hosting-highlights-live-mc",
    title: "Hosting Highlights — Live MC & Cultural Hosting",
    client: "Multiple",
    category: "Live Hosting",
    year: 2024,
    hero: "/portfolio/portfolio-07.jpg",
    gallery: ["/portfolio/portfolio-07.jpg", "/portfolio/portfolio-14.jpg", "/instagram-events/event-12.jpg"],
    video: "/media/portfolio-videos/hosting-highlights.mp4",
    brief: "A compilation of hosting work across cultural and corporate events — where the MC bridges languages, traditions and audiences without missing a beat.",
    scope: ["MC and host sourcing (bilingual Tamil-English, Tamil-Hindi)", "Script and run-of-show preparation", "Rehearsal and timing drills", "Audience-interaction choreography"],
    story: "Hosting isn't about speaking — it's about connecting hearts, cultures and people. We maintain a roster of trained MCs who move fluently across Tamil, English, Hindi and know when to step back and let the moment breathe.",
    outcome: "Multiple repeat bookings; MC roster has grown through word-of-mouth recommendations in the Chennai event community.",
    related: ["cio-association-corporate-performance", "octave-festival-north-east", "accsys-5th-annual-fest"],
  },
  {
    slug: "luxury-car-launch-chennai",
    title: "Luxury Car Launch — Reveal Night",
    client: "Automotive (confidential)",
    category: "Product Launches",
    year: 2024,
    hero: "/portfolio/portfolio-02.jpg",
    gallery: ["/portfolio/portfolio-02.jpg", "/portfolio/portfolio-04.jpg", "/portfolio/portfolio-11.jpg"],
    brief: "A luxury automotive product reveal in Chennai with a theatrical veil-drop, synchronised pyro and press media coverage for an exclusive dealer and press audience.",
    scope: ["Reveal choreography design", "Custom stage and LED backdrop", "Pyro and sparkler column design", "Press and dealer coordination", "Livestream and social coverage"],
    story: "A premium car launch lives or dies on the five seconds of reveal. We designed a veil-drop timed to a scored music cue, with pyro columns igniting on the beat, programmed lighting that lifted the brand's identity colour onto the stage, and a press pit that captured the moment from three angles.",
    outcome: "The reveal cut became the brand's launch-week hero content across their India social.",
    related: ["cio-association-corporate-performance", "accsys-5th-annual-fest", "blm-housing-grand-birthday"],
  },
  {
    slug: "corporate-conference-ballroom-chennai",
    title: "Corporate Conference — Ballroom Production",
    client: "Enterprise (confidential)",
    category: "Conferences & Seminars",
    year: 2024,
    hero: "/portfolio/portfolio-07.jpg",
    gallery: ["/portfolio/portfolio-07.jpg", "/portfolio/portfolio-15.jpg", "/portfolio/portfolio-14.jpg"],
    brief: "Full ballroom production for a Chennai enterprise conference — 600 delegates, two days of programming, hybrid livestream for international attendees.",
    scope: ["Conference stage and LED wall design", "Delegate seating and flow design", "Lighting and sound engineering", "Livestream production", "Media and delegate hospitality", "Breakout room and lunch programming"],
    story: "Enterprise conferences live and die on the schedule. We ran this one with a dedicated showcaller, synchronised keynote slides, lower-thirds on livestream, and a second-screen for timers so no speaker ran over. Breakouts opened and closed on time; lunch was ready to the minute.",
    outcome: "Delegate NPS 87. Hybrid livestream completed with zero A/V drops across both days.",
    related: ["cio-association-corporate-performance", "accsys-5th-annual-fest", "octave-festival-north-east"],
  },
];
