export type Service = {
  slug: string;
  title: string;
  short: string;
  hero: string;
  tagline: string;
  intro: string;
  keyword: string;
  secondary: string[];
  bullets: string[];
  faq: { q: string; a: string }[];
  cta: string;
};

export const services: Service[] = [
  {
    slug: "event-management-chennai",
    title: "Event Management Company in Chennai",
    short: "Event Management",
    hero: "/portfolio/portfolio-07.jpg",
    tagline: "Full-service event management for Chennai's most ambitious brands and families, since 2002.",
    intro: "From 50-guest boardrooms to 2000-guest conferences, Aerollerz plans, designs and runs events end-to-end. Our team of producers, designers, stage specialists and on-ground crew covers every piece — so you walk in as a guest, not a vendor manager.",
    keyword: "event management company in Chennai",
    secondary: ["event management services Chennai", "event planners in Chennai", "event organisers in Chennai"],
    bullets: [
      "Corporate conferences, product launches, award nights, dealer meets, AGMs",
      "Weddings, engagements, receptions, cultural ceremonies",
      "Brand activations, mall roadshows, exhibition builds",
      "Entertainment programming, stage design, lighting, AV production",
      "Vendor coordination, catering, hospitality, logistics, security",
      "Media production, photography, videography, aerial coverage, live streaming",
    ],
    faq: [
      { q: "How much does event management cost in Chennai?", a: "Our events start from ₹2 lakh for intimate functions and go up to ₹2 crore+ for full-scale corporate conferences and luxury weddings. Final pricing depends on guest count, duration, venue, décor, entertainment and production needs. We provide line-item quotes after a 20-minute consultation." },
      { q: "How far in advance should we book?", a: "For large events (300+ guests, luxury weddings, major corporate), book 3-6 months ahead. For focused events we can turn around in 2-4 weeks. For emergencies, we've delivered in 7 days — ask and we'll tell you honestly if it's possible." },
      { q: "Do you handle outstation events?", a: "Yes. We produce events across Tamil Nadu, Pondicherry, Bangalore and have travelled nationally for corporate clients and destination weddings." },
      { q: "What's included in a full-service package?", a: "Pre-event planning, venue coordination, décor design and build, stage and AV, entertainment booking, catering coordination, guest management, on-ground crew, cleanup and post-event reporting with photos and videos." },
    ],
    cta: "Request a Proposal",
  },
  {
    slug: "wedding-planning-chennai",
    title: "Wedding Planners in Chennai",
    short: "Wedding Planning",
    hero: "/portfolio/portfolio-06.jpg",
    tagline: "Chennai wedding planners who handle every function so your family can show up and celebrate.",
    intro: "Muhurtham, engagement, mehendi, sangeet, reception — one team, one plan, one point of contact. We've planned Chennai weddings since 2002, which means we know every venue, every reliable vendor, every muhurtham hall quirk, and every rookie mistake that costs families money.",
    keyword: "wedding planners in Chennai",
    secondary: ["wedding event management Chennai", "best wedding planners Chennai", "wedding planning services Chennai"],
    bullets: [
      "End-to-end wedding planning across all functions",
      "Venue scouting + booking + negotiation",
      "Décor design: mandap, stage, floral, lighting, entry",
      "Catering coordination (South Indian, North Indian, continental, Jain)",
      "Entertainment: DJ, live band, dance choreography, hosts",
      "Guest hospitality, transport, accommodation, hampers",
      "Photography and videography teams",
      "Pre-event rehearsals and timeline management",
    ],
    faq: [
      { q: "What does your wedding planning package include?", a: "Full-service planning covers consultation, concept, venue, décor, catering coordination, entertainment, logistics, guest management, on-ground crew and post-event handover. We also offer partial planning (venue + décor only) and day-of coordination." },
      { q: "Can you work with my preferred venue?", a: "Yes. We've worked at ITC Grand Chola, Leela Palace, Taj Coromandel, Hyatt Regency, Hilton, Feathers, GRT Grand and most Chennai kalyana mandapams. If your venue is new to us, we scout it in person before the event." },
      { q: "Can you plan a destination wedding?", a: "Yes — Pondicherry, Mahabalipuram, Kodaikanal, Bengaluru, Jaipur and Udaipur destinations handled. We travel our core team and partner with trusted local vendors." },
      { q: "What's your minimum wedding budget?", a: "Our wedding productions start from ₹8 lakh (venue, décor, planning for a single function) and go up to ₹2 crore for luxury multi-day weddings. Transparent breakdowns given upfront." },
    ],
    cta: "Book a Consultation",
  },
  {
    slug: "wedding-decoration-chennai",
    title: "Wedding Decorators in Chennai",
    short: "Wedding Decoration",
    hero: "/portfolio/portfolio-03.jpg",
    tagline: "Chennai wedding décor — mandap, stage, floral, lighting — designed to be remembered.",
    intro: "Our in-house design team covers traditional, floral, luxury, minimalist and themed décor across every function. We design to the venue, source florals fresh, build structures that stand up to Chennai humidity, and set up on time — every time.",
    keyword: "wedding decorators in Chennai",
    secondary: ["wedding decoration Chennai", "muhurtham decoration Chennai", "wedding décor Chennai"],
    bullets: [
      "Mandap design — traditional, modern, fusion, themed",
      "Stage décor for reception, sangeet, engagement",
      "Entry arches, pathways, welcome zones",
      "Floral installations — fresh roses, orchids, lilies, jasmine, imported florals",
      "Lighting design — uplight, chandeliers, fairy lights, LED walls",
      "Mandap seating, head table, sweetheart table, lounge zones",
      "Dismantle and cleanup included",
    ],
    faq: [
      { q: "How much does wedding decoration cost in Chennai?", a: "Minimal décor starts around ₹80,000. A full muhurtham mandap with floral and lighting typically runs ₹1.5-5 lakh. Luxury productions can run ₹15 lakh+. We quote itemised: mandap, stage, floral, lighting, entry — you see where every rupee goes." },
      { q: "Do you decorate at any venue?", a: "Yes — hotels, kalyana mandapams, resorts, outdoor venues, home weddings. We scout new venues in advance to pre-plan access and setup." },
      { q: "Can you source specific flowers?", a: "Yes. We work with Chennai's largest flower suppliers for roses, orchids, lilies, carnations, chrysanthemums, jasmine. Imported florals (hydrangea, peony, baby's breath) arranged with 7 days' notice." },
      { q: "How long does setup take?", a: "A standard mandap takes 4-6 hours; a full-day reception setup takes 8-10 hours. We handle overnight setups for morning muhurthams." },
    ],
    cta: "Request a Décor Quote",
  },
  {
    slug: "event-decoration-chennai",
    title: "Event Decorators in Chennai",
    short: "Event Decoration",
    hero: "/portfolio/portfolio-01.jpg",
    tagline: "Event décor for corporate conferences, product launches, award nights and private celebrations.",
    intro: "Beyond weddings, Aerollerz is Chennai's go-to décor team for corporate events, cultural festivals and private celebrations. We've built sets for Ministry of Culture, CIO Association and some of Chennai's largest brand activations.",
    keyword: "event decorators in Chennai",
    secondary: ["event decoration services Chennai", "corporate event decoration Chennai"],
    bullets: [
      "Corporate event sets and stage design",
      "Product launch reveal setups (hydraulic, curtain drop, pyro)",
      "Award ceremony staging and backdrops",
      "Brand activation booths and installations",
      "Cultural event décor (classical, folk, traditional)",
      "Private party and birthday themes",
      "Full lighting + audio + visual design",
    ],
    faq: [
      { q: "Do you decorate at the venue or custom build?", a: "Both. We work at hotels, convention centres, outdoor venues, offices — and we also build custom structures (stages, booths, truss setups) in our workshop and install on-site." },
      { q: "Can you decorate for a single evening event?", a: "Yes. Minimum spend for a focused event décor is around ₹60,000; larger productions scale from there." },
      { q: "Do you provide the AV/lighting too?", a: "Yes — in-house sound, moving lights, LED walls, haze, pyro effects. Everything from one team." },
    ],
    cta: "Get an Event Décor Quote",
  },
  {
    slug: "corporate-event-management-chennai",
    title: "Corporate Event Management in Chennai",
    short: "Corporate Events",
    hero: "/portfolio/portfolio-14.jpg",
    tagline: "B2B event management trusted by CIO Association, Accsys, PFC and Ministry of Culture.",
    intro: "Chennai's enterprises choose Aerollerz for conferences, dealer meets, product launches and award ceremonies because we understand the stakes — timing, keynote flow, media coverage, VIP handling, compliance. Our corporate team runs tight ship events for 50 to 2000 guests.",
    keyword: "corporate event management Chennai",
    secondary: ["B2B event planner Chennai", "conference organiser Chennai", "corporate event company Chennai"],
    bullets: [
      "Annual conferences and summits",
      "Product and brand launches",
      "Dealer and channel-partner meets",
      "AGMs and investor meets",
      "Award ceremonies and recognition programs",
      "Corporate training and offsites",
      "Trade shows, exhibitions and roadshows",
      "Hybrid and virtual event production",
    ],
    faq: [
      { q: "Can you handle 1000+ guest conferences?", a: "Yes. We've produced events for Octave Festival (Ministry of Culture — 2000+ attendees across North East delegations), Accsys 5th Annual Fest and CIO Association performances." },
      { q: "Do you provide AV, lighting and stage in-house?", a: "Yes. We own our core AV and lighting kit and partner with Chennai's top rental houses for scale events. Stage and set builds are handled by our in-house workshop." },
      { q: "Can you manage pan-India corporate roadshows?", a: "Yes. We've travelled roadshow productions across Tamil Nadu, Karnataka, Andhra Pradesh, Kerala and Maharashtra for corporate clients." },
      { q: "How do you handle compliance and safety?", a: "Fire safety clearance, crowd management, backup power, medical standby, VIP security coordination — handled by our ops team as standard for any event over 300 guests." },
    ],
    cta: "Request a Corporate Proposal",
  },
  {
    slug: "engagement-decoration-chennai",
    title: "Engagement Decoration in Chennai",
    short: "Engagement Décor",
    hero: "/portfolio/portfolio-10.jpg",
    tagline: "Engagement décor — stage, backdrop, entry, floral — designed around your theme.",
    intro: "An engagement is the first big function — guests judge the whole wedding on it. We design stages that photograph beautifully, source florals that stay fresh under lights, and build backdrops that your reception photographer will thank you for.",
    keyword: "engagement decoration Chennai",
    secondary: ["engagement stage decoration Chennai", "engagement décor planner Chennai"],
    bullets: [
      "Engagement stage design and backdrop",
      "Mandap and ring exchange setup",
      "Entry arches and welcome signage",
      "Table décor and centerpieces",
      "Floral installations",
      "Lighting and ambient effects",
      "Photo-booth and selfie wall options",
    ],
    faq: [
      { q: "How much does engagement decoration cost in Chennai?", a: "Engagement décor typically ranges from ₹60,000 (minimal setup) to ₹4 lakh (full stage + floral + lighting + entry). Most Chennai engagements land between ₹1.2-2.5 lakh." },
      { q: "Can we see samples before booking?", a: "Yes. We send mood boards, 3D renders and past engagement photos. Final design is signed off before setup begins." },
      { q: "What's your lead time?", a: "Minimum 2 weeks for custom builds; 7 days for ready-stock décor styles." },
    ],
    cta: "Get an Engagement Quote",
  },
  {
    slug: "reception-decoration-chennai",
    title: "Reception Decoration in Chennai",
    short: "Reception Décor",
    hero: "/portfolio/portfolio-03.jpg",
    tagline: "Reception décor — stage, entry, head table, lighting — designed for 100 to 2000 guests.",
    intro: "A reception is a performance — guests arrive, flow through zones, judge every detail. We design stages that work from the back of the hall, entry experiences that set tone, lighting that flatters guests on camera, and lounge zones so the elderly aren't stuck on folding chairs.",
    keyword: "reception decoration Chennai",
    secondary: ["reception stage decoration Chennai", "wedding reception décor Chennai"],
    bullets: [
      "Reception stage design (traditional, modern, themed)",
      "Entry experience and guest welcome zone",
      "Head table and sweetheart lounge",
      "Guest table centerpieces",
      "Lighting — uplight, chandeliers, LED walls",
      "Ambient floral and foliage styling",
      "Photo zones and selfie corners",
    ],
    faq: [
      { q: "How much does reception decoration cost in Chennai?", a: "Reception décor ranges from ₹1.5 lakh (minimal stage + entry) to ₹20 lakh+ for luxury productions. Guest count, venue size and floral spec drive the number." },
      { q: "Can you decorate the whole venue, not just the stage?", a: "Yes — entry pathway, foyer, stage, head table, guest tables, buffet area, exit zone. We can design one consistent language across the whole venue." },
      { q: "Do you work on an overnight setup?", a: "Routinely. Most Chennai receptions need overnight prep; our crew is used to the hours." },
    ],
    cta: "Request a Reception Quote",
  },
  {
    slug: "birthday-event-planners-chennai",
    title: "Birthday Event Planners in Chennai",
    short: "Birthday & Private",
    hero: "/portfolio/portfolio-12.jpg",
    tagline: "Birthday planners for kids, adults and milestone celebrations — themed, run end-to-end.",
    intro: "First birthdays, 60ths, surprise 40ths, BLM Housing Society's founder birthday — we've planned the lot. Themes, décor, entertainment, catering coordination, cake moments, dance acts — one team, all of it.",
    keyword: "birthday event planners Chennai",
    secondary: ["kids birthday party planner Chennai", "private event planner Chennai"],
    bullets: [
      "Kids themes — superhero, princess, cartoon, dinosaur, dreamland",
      "Adult milestone events — 25th, 40th, 50th, 60th",
      "Surprise party planning and venue coordination",
      "Entertainment — magicians, dance acts, mascots, DJ",
      "Themed décor, balloon artistry, cake table styling",
      "Catering coordination (home chefs or venue catering)",
      "Photography, videography, kids photo booth",
    ],
    faq: [
      { q: "How much does a kids birthday party cost in Chennai?", a: "Themed kids parties run ₹35,000 (basic setup, 25 guests) to ₹2 lakh (full theme, entertainment, catering, 100 guests). Adult milestone events typically start at ₹1.5 lakh." },
      { q: "Can you plan a surprise party?", a: "Yes — we've planned dozens. We liaise entirely with the organiser, use neutral venue names in communications, and coordinate guest arrival." },
      { q: "Do you handle at-home parties?", a: "Yes. We bring décor, entertainment, and crew to your home for setups up to 60 guests." },
    ],
    cta: "Plan a Birthday",
  },
  {
    slug: "luxury-wedding-decoration-chennai",
    title: "Luxury Wedding Decorators in Chennai",
    short: "Luxury Weddings",
    hero: "/portfolio/portfolio-06.jpg",
    tagline: "Luxury wedding décor for high-budget productions — bespoke, imported, five-star.",
    intro: "For weddings where every detail is bespoke. Custom-built mandaps, imported florals, five-star venue partnerships (ITC, Leela, Taj, Hyatt), couture floral installations and lighting rigs that transform a ballroom into a cinematic set.",
    keyword: "luxury wedding decorators Chennai",
    secondary: ["high-end wedding décor Chennai", "premium wedding planner Chennai"],
    bullets: [
      "Bespoke mandap and stage design (custom-fabricated)",
      "Imported florals — hydrangea, peony, orchid walls, roses from Ecuador",
      "Chandelier and crystal installations",
      "Custom lighting rigs and projections",
      "Theatre-grade sound and stage",
      "Luxury venue coordination (ITC, Leela, Taj, Hyatt, Hilton)",
      "International-standard crew and timeline execution",
    ],
    faq: [
      { q: "What qualifies as luxury?", a: "Our luxury tier starts at ₹25 lakh for décor alone. Full-production luxury weddings run ₹1-2 crore including planning, décor, entertainment, hospitality and photography." },
      { q: "Can you work with my venue of choice?", a: "Yes. We have working relationships with every five-star hotel in Chennai and have delivered destination luxury weddings in Pondicherry, Goa, Jaipur and Udaipur." },
      { q: "What's the planning timeline?", a: "Luxury wedding bookings begin 6-12 months in advance. We allocate a dedicated producer and designer and meet weekly from month -3." },
    ],
    cta: "Book a Private Consultation",
  },
  {
    slug: "product-launch-management-chennai",
    title: "Product Launch Event Management in Chennai",
    short: "Product Launches",
    hero: "/portfolio/portfolio-02.jpg",
    tagline: "Product launches with reveal moments that get your brand on the news cycle.",
    intro: "Automotive launches, tech launches, FMCG rollouts — Aerollerz builds the stage, scripts the reveal, briefs the media and runs the day. Think hydraulic reveals, pyro moments, countdown videos, press kits — all in one brief.",
    keyword: "product launch event Chennai",
    secondary: ["brand launch event planner Chennai", "product reveal event Chennai"],
    bullets: [
      "Launch concept and reveal choreography",
      "Custom-built reveal mechanics (curtain drop, hydraulic, pyro, light reveal)",
      "Stage, LED walls, lighting, sound",
      "Media briefing kits and press coordination",
      "Celebrity, influencer and MC booking",
      "Guest and dealer invite management",
      "Livestream and social coverage",
    ],
    faq: [
      { q: "Can you deliver pyro, hydraulic reveals, and complex staging?", a: "Yes. We've produced automotive launches with hydraulic lift reveals, pyro columns and synchronised LED+light choreography." },
      { q: "Do you coordinate press and media?", a: "Yes — invite management, press kits, embargo coordination, livestream for digital reach." },
      { q: "What's the typical production timeline?", a: "6-10 weeks for a major product launch; 3-4 weeks for an internal reveal." },
    ],
    cta: "Request a Launch Proposal",
  },
];
